info=["uno, いち, いつ, ヒト",
"encima, うえ",
"debajo, inferior, した, しも, もと, さが(る), くだ(す), お(ろす)",
"no (prefijo), ふ、　ぶ",
"poco, pequeño, すこ(し)、　すく(ない)、　ショウ",
"dentro, centro, なか, うち, あた(る), チュウ",
"siete, なな, シチ",
"señor, maestro, amo, ぬし, あるじ, シュ, シュウ",
"año, とし, ネン",
"nueve, ここの, ク, キュウ",
"cosa, asunto, razón, hecho, こと, つか(う), ジ",
"dos, ニ, ふた",
"tres, サン, み(つ)",
"mundo, generación, セイ, セ, ",
"mucho tiempo, ひさ(しい)",
"decir, いう, ウン",
"cinco, ゴ, いつ(つ)",
"corazón, espíritu, こころ, シン",
"capital, キョウ, みやこ",
"persona, ひと, ジン, ニン",
"ahora, いま, コン",
"otro, ほか, タ",
"adjuntar, acompañar, つ(く), つ(け),つ(きあい)",
"agua, みず, スイ",
"comparado con, en vista de, イ(ガイ)",
"boca, くち, コウ, ク",
"rango, grado, イ, くらい, ぐらい",
"hacer, preparar, construir, つく(る), サク, サ",
"ojo, ver, め, モク",
"conocer, saber, conocimiento, し(る), チ"]